apiVersion: v2
name: vllm-demo
description: vLLM + Streamlit in one chart, with ingress-nginx dependency (NodePort 8000 to localhost)
type: application
version: 0.1.1
appVersion: "1.0.0"
dependencies:
  - name: ingress-nginx
    version: "4.11.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress-nginx.enabled
