apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: {{ .Values.vllm.name }}
spec:
  type: ClusterIP
  selector:
    app: vllm
  ports:
    - name: http
      port: 8000
      targetPort: 8000