apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vllm.name }}
  namespace: {{ .Values.vllm.name }}
spec:
  replicas: {{ .Values.vllm.replicas }}
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      enableServiceLinks: false 
      containers:
        - name: vllm
          image: substratusai/vllm:main-cpu
          imagePullPolicy: IfNotPresent

          command:
            - python3
            - -m
            - vllm.entrypoints.openai.api_server
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"
            - "--model"
            - {{ .Values.vllm.model.name }}
            - "--device"
            - "cpu"
            - "--dtype"
            - {{ .Values.vllm.dtype }}
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: {{ .Values.vllm.resources.requests.cpu }}
              memory: {{ .Values.vllm.resources.requests.memory }}
            limits:
              cpu: {{ .Values.vllm.resources.limits.cpu }}
              memory: {{ .Values.vllm.resources.limits.cpu }}
          readinessProbe:
            httpGet:
              path: /v1/models
              port: http
            initialDelaySeconds: 200
            timeoutSeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 200
            timeoutSeconds: 5
            periodSeconds: 20
---
